version: '3.4'

services:

  bookingdb:
    image: mongo

  activitiesdb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4

  booking.api:
    image: ${DOCKER_REGISTRY-}bookingapi
    build:
      context: .
      dockerfile: Services/Bookings/Booking.API/Dockerfile

  activities.api:
    image: ${DOCKER_REGISTRY-}activitiesapi
    build:
      context: .
      dockerfile: Services/Activities/Activities.API/Dockerfile

volumes:
  mongo_data: 
  postgres_data:
  pgadmin_data:
